### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by liupeng0518** [larsks/dot-iptables#10]
how to install it? thanks.

**Comment by larsks** [comment]
It's a standard Python package, so if you have it cloned locally you can just run:

```
pip install .
```
Or you can install it directly from github:

```
pip install git+https://github.com/larsks/dot-iptables
```

And then run it like:

```
sudo iptables-save | dotiptables
```

This will generate files `nat.dot`, `filter.dot`, and `mangle.dot` in your current directory. If you add the `--render` option it will also generate svg output.

**Comment by liupeng0518** [comment]
```
root@node1:~# pip3 install git+https://github.com/larsks/dot-iptables
Collecting git+https://github.com/larsks/dot-iptables
  Cloning https://github.com/larsks/dot-iptables to /tmp/pip-3ijav6ja-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-3ijav6ja-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-3ijav6ja-build/
root@node1:~#
```

**Comment by liupeng0518** [comment]
and add setup.py
```
#!/usr/bin/env python

import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

it`s ok,but run command error:
```
root@node1:/vagrant_data/dot-iptables/dot# iptables-save | dotiptables --render
Reading iptables data.
Generating DOT output.
Generating SVG output.
Traceback (most recent call last):
  File "/usr/local/bin/dotiptables", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/dotiptables/__main__.py", line 178, in main
    render_svg(iptables, opts)
  File "/usr/local/lib/python3.6/dist-packages/dotiptables/__main__.py", line 155, in render_svg
    os.path.join(opts.outputdir, '%s.dot' % table)])
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'
```

**Comment by larsks** [comment]
Ah, interesting. I've stopped using `setup.py` in my Python projects, but I guess `pip` still relies on that for `git+https://` installs. I guess just clone and `pip install .`, then.

> FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

You haven't installed `graphviz`, which provides the `dot` command.
